### PR TITLE
Copilot Prompt to fetch top 10 bullet points from a document

### PR DESCRIPTION
**Pull request by SandeepPothedar**
Copilot Prompt to fetch top 10 bullet points from a document - Easy prompt but a very useful prompt where you just want to grab the synopsis/summary of the document

### CODE REVIEW

**Comment by rabwill** [comment]
Thanks @SandeepPothedar !

**Comment by PopWarner** [comment]
🎉✨ Woohoo! ✨🎉

Thank you @SandeepPothedar for your awesome contribution to the community with this merged PR! 🚀 You've earned a Credly badge through the Microsoft 365 & Power Platform Recognition Program. 🏅 To receive your badge, please take a moment to opt in to the program. You can learn more and sign up here: https://aka.ms/community/recognition.

Can't wait to see you in the program! 🎊

Cheers,
David Warner 🧡💜

cc: @rabwill

**Comment by SandeepPothedar** [comment]
I have signed up for the Program David

Regards Sandeep Pothedar

**Comment by SandeepPothedar** [comment]
Hey Rabia/David
Hope you guys are doing great !
Is the Digital badge program still on ? I wanted to showcase my earlier
badge on my Linkedin profile ,but somehow never received it .

**Pull request merged**
