### PR TITLE
Added: m365-yearly-performance-review-prompt

### PR DESCRIPTION
**Pull request by UnsuckM365**
Added prompt to create List of Accomplishments for Yearly Performance Review.

By Diego Domingos da Silva 
@UnsuckM365

### CODE REVIEW

**Comment by UnsuckM365** [comment]
Hi @rabwill -- can you kindly let me know why this is failing validation? Thanks a ton!

**Comment by UnsuckM365** [comment]
> Hi @rabwill -- can you kindly let me know why this is failing validation? Thanks a ton!

Nevermind I figured it out :-)

**Comment by rabwill** [comment]
Thanks @UnsuckM365 :) will merge shortly glad you figured the issue !

**Comment by rabwill** [comment]
This prompt is helpful, but it seems a bit broad, which might be why for me the Copilot isn’t providing accurate results. Could we refine it to focus on specifics? For example, asking about work ethics displayed in meetings or improvements in communication style could get better results and reduce the chance of hallucination. Let me know your thoughts @UnsuckM365 :)

**Comment by UnsuckM365** [comment]
This has been working very well for me and my colleagues, but we practically live on Teams. Are you able to commit this so I can share it on LinkedIn and X for feedback from other friends in the community?

**Pull request merged**
