### PR TITLE
New sample : M365 fluency timing coach prompt

### PR DESCRIPTION
**Pull request by ferrarirosso**
Hello

I find this prompt helpful when I had to prepare for my first community call last week :-)

Hope this helps
Kind regards
Nello

### CODE REVIEW

**Comment by rabwill** [comment]
Thanks so much @ferrarirosso :) this is EXTREMELY cool scenario! Would you be interested in collaborating to show this as a demo in one of the calls?

**Comment by ferrarirosso** [comment]
Hello @rabwill 

Thank you! I’m glad I could contribute.

I’m scheduled for the following SPFx & Viva Community calls:
- September 19
- October 17
- October 31
If showcasing this scenario fits the agenda for any of these calls, I’d be happy to demonstrate it live. Perhaps you could check with Vesa Juvonen to see if that’s feasible? If not, we could also record a quick video to share the demo.

Looking forward to collaborating!

**Comment by rabwill** [comment]
Hi @ferrarirosso ,
These are calls for SPFx specifically and may not be suited to show prompts. I checked with Vesa as well. Best idea is to do a YT shorts ( and I can help you with that ☺️)

**Comment by ferrarirosso** [comment]
Hi @rabwill 

Great, never done a YT, so your help will be much appreciated !

**Comment by rabwill** [comment]
I will pull in David Warner, the star too into this chat as he is a master video creator. @PopWarner welcome <3

**Pull request merged**
